### ISSUE TITLE
Rebooting MaptimeCHA

### ISSUE THREAD

**Issue by geobrando** [maptime/chattanooga#9]
So @rjhale1971 has stepped up and wants to help get MaptimeCHA up and running again.  Are any of you still living in the area and would like to be involved?  Do any of you have access to the twitter account?

@jden @kylegordy @seabre

**Comment by rjhale1971** [comment]
If you want to be involved please do - I'll take the brunt of the fun for a while to get it up and going. I've got a plan of sorts rolling around in my head.

**Comment by junosuarez** [comment]
I made sure @seabre had access to the twitter credentials & can share with whoever needs it. I'm gonna close this issue :)

**Comment by seabre** [comment]
@jden I don't have those credentials.

**Comment by junosuarez** [comment]
ah- maybe it was @aplannersguide

**Comment by geobrando** [comment]
So are you guys good to go on the twitter credentials?  If not, perhaps @jden you could give them again to someone else.

**Comment by aplannersguide** [comment]
@geobrando @jden @seabre I gave the info to @rhhale1971 so I think we should be good now.

**Comment by geobrando** [comment]
:+1:
